name: API Manual

on:
  workflow_dispatch:
    inputs:
      environment:
        description: Environment
        required: true
        type: choice
        options:
          - develop
          - test

jobs:
  api-tests:
    uses: ./.github/workflows/api.yml
    with:
      environment: ${{ github.event.inputs.environment }}